

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
      APP_SECRET: "ChangeMeToASecureValue"
      DATABASE_URL: "mysql://user:password@db:3306/car_workshop"
      VEHICLE_API_URL: "https://www.carqueryapi.com/api/0.3/"
    user: "www-data"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_workshop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
