<?php

namespace Container7Igkg92;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppointmentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AppointmentController' shared autowired service.
     *
     * @return \App\Controller\AppointmentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AppointmentController.php';

        $container->services['App\\Controller\\AppointmentController'] = $instance = new \App\Controller\AppointmentController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\AppointmentController', $container));

        return $instance;
    }
}
