<?php

namespace Container7Igkg92;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVehicleApiServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\VehicleApiService' shared autowired service.
     *
     * @return \App\Service\VehicleApiService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/VehicleApiService.php';

        return $container->services['App\\Service\\VehicleApiService'] = new \App\Service\VehicleApiService(($container->services['Symfony\\Contracts\\HttpClient\\HttpClientInterface'] ?? $container->load('getHttpClientInterfaceService')));
    }
}
