services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Symfony\Contracts\HttpClient\HttpClientInterface: '@http_client'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Tests/'
            - '../src/Kernel.php'
            - '../src/Utils/'  # 👈 Añadido para evitar cargar funciones como servicios

framework:
  cache:
    pools:
      doctrine.system_cache_pool:
        adapter: cache.system
      doctrine.result_cache_pool:
        adapter: cache.app
