services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Symfony\Contracts\HttpClient\HttpClientInterface: '@http_client'

    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'
