<?php

namespace Container3ERJ0Vq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_47u4zNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.47u4z_N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.47u4z_N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'vehicleApiService' => ['privates', '.errored..service_locator.47u4z_N.App\\Service\\VehicleApiService', NULL, 'Cannot autowire service ".service_locator.47u4z_N": it references class "App\\Service\\VehicleApiService" but no such service exists.'],
        ], [
            'vehicleApiService' => 'App\\Service\\VehicleApiService',
        ]);
    }
}
