<?php

namespace Container3ERJ0Vq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVehicleApiServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.47u4z_N.App\Service\VehicleApiService' shared service.
     *
     * @return \App\Service\VehicleApiService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.47u4z_N": it references class "App\\Service\\VehicleApiService" but no such service exists.');
    }
}
