<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7Igkg92\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7Igkg92/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7Igkg92.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7Igkg92\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7Igkg92\App_KernelDevDebugContainer([
    'container.build_hash' => '7Igkg92',
    'container.build_id' => 'a5cc8367',
    'container.build_time' => 1742836282,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container7Igkg92');
