<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUBIj1kU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUBIj1kU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUBIj1kU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUBIj1kU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUBIj1kU\App_KernelDevDebugContainer([
    'container.build_hash' => 'UBIj1kU',
    'container.build_id' => 'e41dc83f',
    'container.build_time' => 1743786822,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUBIj1kU');
