<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_vehicle_models' => [[], ['_controller' => 'App\\Controller\\ApiController::getVehicleModels'], [], [['text', '/api/vehicle-models']], [], [], []],
    'appointments' => [[], ['_controller' => 'App\\Controller\\AppointmentController::list'], [], [['text', '/appointments']], [], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\ApiController::getVehicleModels' => [[], ['_controller' => 'App\\Controller\\ApiController::getVehicleModels'], [], [['text', '/api/vehicle-models']], [], [], []],
    'App\Controller\AppointmentController::list' => [[], ['_controller' => 'App\\Controller\\AppointmentController::list'], [], [['text', '/appointments']], [], [], []],
    'App\Controller\DefaultController::index' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], [], []],
];
